import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pascal | Linktree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            marginBottom: "20px",
            position: "relative",
            width: "100%",
            maxWidth: "1152px",
            // border: "1px solid red"
          }}
        >
          <Image
            src={"/assets/pascal.jpg"}
            width={88}
            height={88}
            alt=""
            className="profile_img"
            id="profile_img"
          />
          <h4 id="twitter">meta_khal</h4>
          <h4 id="slack" style={{display: "none"}}>Khal</h4>
          <Image src={"/assets/share.png"} width={40} height={40} alt="" className="desktop_share" />
          <Image src={"/assets/share.svg"} width={40} height={40} alt="" className="mobile_share" />
        </div>

        <div className="link_section">
          <Link href={"https://twitter.com/meta_khal"} legacyBehavior>
            <a className="link" >Twitter Link</a>
          </Link>

          <Link href={"https://training.zuri.team/"} legacyBehavior>
            <a className="link" id="btn_zuri">Zuri Team</a>
          </Link>

          <Link href={"http://books.zuri.team/"} legacyBehavior>
            <a className="link" id="books">Zuri books</a>
          </Link>

          <Link href={"https://books.zuri.team/python-for-beginners?ref_id=khal"} legacyBehavior>
            <a className="link" id="book_python">Python Books</a>
          </Link>

          <Link href={"https://background.zuri.team/"} legacyBehavior>
            <a className="link" id="pitch">Background Check for Coders</a>
          </Link>

          <Link href={"https://books.zuri.team/design-rules"} legacyBehavior>
            <a className="link" id="book_design">Design Books</a>
          </Link>
        </div>

        <div style={{maxWidth: "1216px", textAlign: "center", marginTop: "30px"}}>
          <Image src={"/assets/slack.png"} width={20} height={20} alt="slack icon" className="icon"  />
          <Link href={"https://github.com/kodecheff"} legacyBehavior>
            <a>
              <Image src={"/assets/github.png"} width={20} height={20} alt="github icon" className="icon" />
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Image src={"/assets/zuri.png"} width={185.03} height={24.74} alt="" />
        <Image src={"/assets/footer txt.png"} width={232.28} height={24} alt="" />
        <Image src={"/assets/I4G.png"} width={132.13} height={32} alt="" />
      </footer>
    </div>
  );
}
